# Here we have to predict the caesarian

In [10]:
import pandas as pd
import numpy as npy
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

df = pd.read_csv('caesarian.csv')

In [11]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [12]:
X.shape, y.shape

((80, 5), (80,))

In [ ]:
from sklearn.preprocessing import OneHotEncoder

categorical_features = ['Age', 'Delivery phase', 'Delivery time', 'Blood pressure', 'Heart problem']
categorical_features = npy.array(categorical_features).reshape(-1, 1)

encoder = OneHotEncoder(sparse_output=False)
encoder_fit = encoder.fit_transform(categorical_features)

In [15]:
print("Encode value:", encoder_fit)

Encode value: [[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
